library(tidyverse)

tmp <- data.frame(orig=names(readxl::read_excel("Tracking Myself Spreadsheet.xlsx",
                                                n_max=1))) |>
  mutate(new=c("Timestamp",
               "training",
               "stress_lvl",
               "stress_src",
               "body_feel",
               "eat_habits",
               "pre_snacks",
               "electrolytes",
               "alcohol",
               "sleep",
               "emotional_reg",
               "pr",
               "have_fun",
               "events",
               "lift",
               "period",
               "focus"))

df <- readxl::read_excel("Tracking Myself Spreadsheet.xlsx",
                         skip=1,col_names=tmp$new) |>
  rename(time=Timestamp) |>
  mutate(mon=lubridate::month(time,label=TRUE,abbr=TRUE),
         day=lubridate::day(time),
         yr=lubridate::year(time),
         hr=lubridate::hour(time),
         day=ifelse(hr<5,day-1,day), # adjust for after midnight entries
         date=paste(mon,day,yr,sep="-"),
         date=as.Date(date,format="%b-%d-%Y"),
         workoutday=factor(ifelse(grepl("Rest",training),"No","Yes"),
                           levels=c("No","Yes")),
         compday=factor(ifelse(grepl("Competition",training),"Yes","No"),
                        levels=c("No","Yes")),
         training=factor(training,levels=c("Rest (little/no activity)",
                                           "Rest day (moderate to high activity)",
                                           "Sprints",
                                           "Jumps",
                                           "Competition"),
                         labels=c("Rest (little/no activity)",
                                  "Rest (moderate to high activity)",
                                  "Sprints",
                                  "Jumps",
                                  "Competition")),
         stress_lvl=factor(stress_lvl,levels=1:5,
                           labels=c("Tears, hanging on",
                                    "Tough, but getting through",
                                    "Tough, but things done",
                                    "Great day, some spots",
                                    "Happy, under control")),
         stress_relationship=ifelse(grepl("Hans",stress_src),"Yes","No"),
         stress_family=ifelse(grepl("Family",stress_src),"Yes","No"),
         stress_friends=ifelse(grepl("Friends",stress_src),"Yes","No"),
         stress_lonely=ifelse(grepl("Lonely",stress_src),"Yes","No"),
         stress_school=ifelse(grepl("School",stress_src),"Yes","No"),
         stress_work=ifelse(grepl("Work",stress_src),"Yes","No"),
         stress_track=ifelse(grepl("Track",stress_src),"Yes","No"),
         stress_tired=ifelse(grepl("Tired",stress_src),"Yes","No"),
         body_feel=factor(body_feel,levels=1:5,
                          labels=c("Sick/Injured/Can't",
                                   "Sore, need trainer",
                                   "Fine, getting it done",
                                   "Good, some kinks",
                                   "Amazing, could PR")),
         eat_habits=factor(eat_habits,levels=1:4,
                           labels=c("Not good, not 3",
                                    "Not good, but 3",
                                    "3, but upset",
                                    "3, and balanced")),
         pre_snacks=factor(pre_snacks,levels=c("No","Only for 1 workout out","Yes"),
                           labels=c("No","Only for 1 workout","Yes")),
         electrolytes01=factor(ifelse(grepl("Yes",electrolytes),"Yes","No"),
                               levels=c("No","Yes")),
         electrolytes=factor(electrolytes,levels=c("No",
                                                   "Yes, only after 1 practice out of two",
                                                   "Yes, during practice",
                                                   "Yes, after practice")),
         electrolytes01=factor(ifelse(grepl("Yes",electrolytes),"Yes","No"),
                               levels=c("No","Yes")),
         alcohol01=factor(ifelse(grepl("Yes",alcohol),"Yes","No"),
                          levels=c("No","Yes")),
         alcohol=factor(alcohol,levels=c("No","Yes (<2)","Yes (>2)")),
         emotional_reg=factor(emotional_reg,levels=1:5,
                              labels=c("Breakdown",
                                       "Some good",
                                       "Some bad",
                                       "Mostly good",
                                       "Flow state")),
         pr=factor(pr,levels=c("No","Season Best","Lifetime PR")),
         have_fun=factor(have_fun,levels=c("No","Sometimes","Yes")),
         lift=factor(lift,levels=c("No","Yes")),
         period=factor(period,levels=c("No","Yes")),
         focus=factor(focus,levels=1:5,
                      labels=c("Elsewhere",
                               "Trying to visualize",
                               "Some focus",
                               "Mostly focused",
                               "Flow state")),
         ev_triple=ifelse(grepl("Triple",events),"Yes","No"),
         ev_long=ifelse(grepl("Long",events),"Yes","No"),
         ev_mult=ifelse(grepl(",",events),"Yes","No")
  ) |>
  select(date,yr,mon,day,
         workoutday,compday,training,lift,
         starts_with("stress"),
         body_feel,period,sleep,
         eat_habits,pre_snacks,electrolytes01,electrolytes,alcohol01,alcohol,
         events,ev_triple,ev_long,ev_mult,
         pr,emotional_reg,have_fun,focus)

dfComp <- df |>
  filter(compday=="Yes")

n <- nrow(df)
