---
title: "Journey's Daily Data"
format: 
  revealjs:
    theme: default
    embed-resources: true
execute:
  echo: false
---

```{r}
#| label: setup
#| results: hide

## Source the data reading and cleaning script
source("Data_Cleanup.R")

## Source the graphics preparation script
source("Graph_Prep.R")
```

# Simple Summaries

## Sleep Daily Series

```{r}
ggplot() +
  geom_line(data=df,mapping=aes(x=date,y=sleep),color="gray85") +
  geom_point(data=df,mapping=aes(x=date,y=sleep,fill=workoutday),
             color="gray10",pch=21) +
  geom_vline(data=dfComp,mapping=aes(xintercept=date),
             color="red",linetype="dotted",linewidth=1) +
  scale_y_continuous(name="Hours of Sleep") +
  scale_x_date(breaks="2 weeks",date_labels="%b-%d") +
  scale_fill_manual(values=c("No"="white","Yes"="gray50")) +
  theme_journey_time +
  theme(axis.title.x=element_blank(),
        legend.position="none") +
  labs(caption="Open points are rest days, red lines are competitions")
```

## Sleep Summary

```{r}
tmp <- df |>
  filter(!is.na(sleep)) |>
  mutate(fsleep=factor(sleep)) |>
  group_by(fsleep) |>
  summarize(freq=n()) |>
  mutate(perc=freq/sum(freq))

ggplot(data=tmp,mapping=aes(x=fsleep,y=perc)) +
  geom_bar(stat="identity",color="gray10",fill="gray80") +
  scale_y_continuous(name=str_glue("Percentage of {sum(tmp$freq)} Days"),
                     expand=expansion(mult=c(0,0.02)),
                     labels=scales::label_percent()) +
  scale_x_discrete(name="Hours of Sleep") +
  theme_journey_time
```

